# Generated by Django 4.1.5 on 2023-01-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_country'),
        ('account', '0003_codelink'),
    ]

    operations = [
    ]
