# Generated by Django 4.1.5 on 2023-01-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_merge_0002_alter_user_country_0003_codelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='World', max_length=2),
        ),
    ]
