# Generated by Django 4.1.5 on 2023-01-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_image_delete_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
